[keyboard]
name = "Enndgame"
product_name = "Enndgame"
vendor_id = 0x5c4c
product_id = 0x5644
manufacturer = "rmk"
chip = "rp2040"

[matrix]
# Input and output pins are mandatory
output_pins  = ["PIN_27", "PIN_29", "PIN_28", "PIN_26", "PIN_15", "PIN_4", "PIN_3", "PIN_0", "PIN_1", "PIN_2"]
input_pins = ["PIN_14", "PIN_13", "PIN_12", "PIN_11"]

[layout]
rows = 4
cols = 10
layers = 5
keymap = [
    [
        ["Q", "W", "E", "R", "T", "Y", "U", "I", "O", "P"],
        ["A", "S", "MT(D, LCtrl)", "MT(F, LShift)", "G", "H", "MT(J, RShift)", "MT(K, RCtrl)", "L", "Semicolon"],
        ["MT(Z, LAlt)", "MT(X, LGui)", "C", "V", "B", "N", "M", "Comma",  "MT(Dot, RGui)",  "MT(Slash, RAlt)"],
        ["LShift", "__", "__", "MO(1)", "Space", "MO(2)", "MO(3)", "__", "__", "RShift"]
    ],
    [
        ["__", "__", "__", "__", "__", "__", "WM(Kc7, LShift)", "WM(Kc8, LShift)", "Quote", "Delete"],
        ["__", "__", "LCtrl", "LShift", "__", "Left", "Down", "UP", "Right", "Grave"],
        ["LAlt", "LGui", "__", "__", "__", "Home", "PageDown",  "PageUp",  "End", "Insert"],
        ["__", "__", "__", "MO(1)", "Space", "MO(2)", "MO(3)", "__", "__", "__"]
    ],
    [
        ["WM(Kc1, LShift)", "WM(Kc2, LShift)", "WM(Kc3, LShift)", "WM(Kc4, LShift)", "WM(Kc5, LShift)", "WM(Kc6, LShift)", "WM(Kc9, LShift)", "WM(Kc0, LShift)", "__", "Delete"],
        ["__", "__", "LCtrl", "LShift", "__", "Equal", "LeftBracket", "RightBracket", "Grave", "Backslash"],
        ["LAlt", "LGui", "__", "__", "__", "Minus", "WM(LeftBracket, LShift)", "WM(RightBracket, LShift)", "__", "WM(Backslash, LShift)"],
        ["__", "__", "__", "MO(4)", "WM(Minus, LShift)", "__", "__", "__", "__", "__"],
    ],
    [
        ["WM(Kc8, LShift)", "Kc7", "Kc8", "Kc9", "WM(Equal, LShift)", "__", "__", "__", "__", "__"],
        ["Backslash", "Kc4", "Kc5", "Kc6", "Equal", "__", "RShift", "RCtrl", "__", "__"],
        ["Kc0", "Kc1", "Kc2", "Kc3", "Minus", "__", "__", "__", "RGui", "RAlt"],
        ["__", "__", "__", "WM(Minus, LShift)", "__", "__", "__", "__", "__", "__"],
    ],
    [
        ["F12", "F7", "F8", "F9", "PrintScreen", "__", "__", "__", "__", "__"],
        ["F11", "F4", "F5", "F6", "__", "__", "__", "__", "__", "__"],
        ["F10", "F1", "F2", "F3", "__", "__", "__", "__", "__", "__"],
        ["__", "__", "__", "__", "__", "__", "__", "__", "__", "__"],
    ],
]

[[behavior.combo.combos]]
actions = ["MT(J, RShift)", "MT(K, RCtrl)"]
output = "Escape"

[[behavior.combo.combos]]
actions = ["MT(K, RCtrl)", "L"]
output = "Enter"

[[behavior.combo.combos]]
actions = ["MT(X, LGui)", "C"]
output = "Tab"

[[behavior.combo.combos]]
actions = ["C", "V"]
output = "Backspace"

[behavior.tap_hold]
enable_hrm = true
hold_timeout = "150ms"
# prior_time_idle = "0ms"
